### ISSUE TITLE
make the participants table responsive on mobile as well as desktop 

### ISSUE THREAD

**Issue by TejasNasre** [TejasNasre/nexmeet#118]
https://github.com/user-attachments/assets/d42ad497-527b-4d98-bbf8-7d30a2993323

**Comment by AlexVCS** [comment]
Hi there, I'd like to work on this issue. Can you assign it to me please?

**Comment by TejasNasre** [comment]
@AlexVCS assigning you make PR asap to dev branch before PR post the working video here

**Comment by AlexVCS** [comment]
I'm trying to setup my dev environment. The `learn.md` file has a lot of steps and I'm not clear on exactly what I should be doing on supabase and what should be happening. The Kinde steps are clear and easy to get setup. When I get to Supabase, I see no mention of where to bring in the password, though I think I saw where to grab that when setting up a new project. Then when we're making tables, is it supposed to run but not create any rows? It would be helpful to get more detailed if there are going to be lots of steps in order to avoid confusion and create a better DX.

**Comment by TejasNasre** [comment]
Yeah there are lot of steps to setup the supabase architecture but it's easy initially it will have no rows and data present Because it's your instance so you need to setup and the fill the event details from your ui and then participate in your own event and test it

**Comment by AlexVCS** [comment]
Are there docs on participating in your event to test it? If not, that would be helpful!

**Comment by TejasNasre** [comment]
@AlexVCS sir ant updates ?

**Comment by yashksaini-coder** [comment]
let me work on this

**Comment by yashksaini-coder** [comment]
@TejasNasre bro I am having trouble in the setup

**Comment by yashksaini-coder** [comment]
I am not going to work on this one

**Comment by TejasNasre** [comment]
okay

**Comment by mehul-m-prajapati** [comment]
Please assign this to me
