### ISSUE TITLE
bug: offline page

### ISSUE THREAD

**Issue by TejasNasre** [TejasNasre/nexmeet#270]
https://github.com/user-attachments/assets/680a319c-ebfa-4343-92da-b0a70de9fec3

fix this @tarunkumar2005 offline page today itself

**Comment by lattaai4** [comment]
Hello, I tried to fix the issue

This is what I did:

Modified the offline.html page to include a more user-friendly message and updated the service worker to handle offline scenarios better.

I also created pull request: https://github.com/TejasNasre/nexmeet/pull/271


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by tarunkumar2005** [comment]
@TejasNasre I need to look into it what is the issue can you give me time like until tomorrow i am bit busy also.

**Comment by TejasNasre** [comment]
okay but please fix this tomorrow morning its easy but i dont know you worked on that so please solve that bug asap

**Comment by TejasNasre** [comment]
@tarunkumar2005 you are working?

**Comment by TarunWebDev** [comment]
@TejasNasre I will not be able to working on this as my account is suspended will gain access again under review so you can assign to someone else.
